#!/bin/bash

# Create the file with touch
touch '*\\'"Best School"'\\*$?*****:)'

# Write and Print "Best School" followed by a new line to the file
echo "Best School" > '*\\'"Best School"'\\*$?*****:)' 
echo "" >> '*\\'"Best School"'\\*$?*****:)'
