#!/bin/bash

# Set up the date and time format for the log entries
date_format="+%d/%b/%Y:%H:%M:%S %z"

# Generate a random IP address for each log entry
function rand_ip() {
  echo "$((RANDOM%256)).$((RANDOM%256)).$((RANDOM%256)).$((RANDOM%256))"
}

# List of possible HTTP methods and status codes for the log entries
methods=(GET POST PUT DELETE HEAD)
statuses=(200 201 204 301 302 304 400 401 403 404 500 502 503 504)

# Loop to generate log entries and write them to a file
for i in {1..1000}; do
  # Randomly choose a HTTP method, status code, and number of bytes transferred
  method=${methods[$((RANDOM%${#methods[@]}))]}
  status=${statuses[$((RANDOM%${#statuses[@]}))]}
  bytes=$((RANDOM%10000))

  # Write the log entry to the file in TSV format
  echo "$(rand_ip) $(date "$date_format") $method /page.html $status $bytes" >> access.log
done
