#!/bin/bash

# Use the id command to get information about the current user
user_info=$(id)

# Extract the list of groups from the user_info string
group_list=$(echo "$user_info" | awk -F'[()]' '{print $4}')

# Print the list of groups
echo "Groups: $group_list"