#!/bin/bash

# Use the chmod command to add permissions to the file hello
chmod u+x hello
chmod g+x hello
chmod o+x hello

# Print a message indicating that the permissions have been changed
echo "Permissions have been updated for file hello successfully."