#!/bin/bash
water_dec=$(echo "ibase=water; ${WATER}" | bc)
stir_dec=$(echo "ibase=stir; ${STIR}" | bc)
result_dec=$((${water_dec} + ${stir_dec}))
result_bestchol=$(echo "obase=bestchol; ${result_dec}" | bc)
echo "${result_bestchol}"
