#!/bin/bash
echo "Local Variables:"
echo "$(set | grep '^[a-zA-Z_][a-zA-Z0-9_]*=')"
echo ""
echo "Environment Variables:"
echo "$(printenv)"
echo ""
echo "Functions:"
echo "$(declare -F | awk '{print $3}')"
